# Generated by Django 3.1.3 on 2020-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20201211_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_sensor',
            name='decription',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
