# Generated by Django 3.1.3 on 2020-12-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201211_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_sensor',
            name='is_sensor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
