# Generated by Django 3.1.3 on 2020-12-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
    ]
