# Generated by Django 3.1.3 on 2020-12-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_device_sensor_is_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('pin_id', models.IntegerField()),
                ('commant', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandRespose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.command')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pin_id', models.IntegerField()),
                ('is_sensor', models.BooleanField()),
                ('decription', models.TextField(blank=True, max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='App.devicesensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device_sensor',
            name='chip',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor',
        ),
        migrations.RenameField(
            model_name='chip',
            old_name='time_create',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='chip',
            old_name='time_update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='number',
            new_name='values',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Device_Sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AddField(
            model_name='devicesensor',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip', to='App.chip'),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='App.devicesensor'),
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='App.sensordata'),
            preserve_default=False,
        ),
    ]
