# Generated by Django 3.1.3 on 2020-12-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
