# Generated by Django 3.1.3 on 2020-12-11 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0008_auto_20201212_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chip', to=settings.AUTH_USER_MODEL),
        ),
    ]
