# Generated by Django 3.1.3 on 2020-12-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201212_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='values',
            new_name='value',
        ),
    ]
