# Generated by Django 3.1.3 on 2020-12-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20201212_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='commant',
            new_name='command',
        ),
    ]
