# Generated by Django 3.1.3 on 2021-01-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_chip_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandrespose',
            name='command_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='App.command'),
        ),
    ]
