# Generated by Django 3.1.3 on 2020-12-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_myusers_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='myuser',
        ),
        migrations.AddField(
            model_name='myusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
